const express = require('express');
const router = express.Router();
const queryController = require('../controllers/queryController');
const uploadController = require('../controllers/uploadController');
const authProvider = require('../services/authProvider');

/**
 * @swagger
 * /api/health:
 *   get:
 *     summary: Health check endpoint
 *     description: Check if the Moogle API server is running and responsive
 *     tags: [Health]
 *     responses:
 *       200:
 *         description: Server is healthy and running
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: ok
 *                 message:
 *                   type: string
 *                   example: Moogle API is running
 *                 timestamp:
 *                   type: string
 *                   format: date-time
 *                   example: 2025-12-01T12:00:00.000Z
 */
router.get('/health', queryController.getHealth);

/**
 * @swagger
 * /api/query:
 *   post:
 *     summary: Process natural language query
 *     description: Convert natural language questions into structured queries and return filtered worker data
 *     tags: [Query]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - query
 *             properties:
 *               query:
 *                 type: string
 *                 description: Natural language question about worker data
 *                 example: Show me all workers from the IT department
 *                 minLength: 3
 *                 maxLength: 500
 *     responses:
 *       200:
 *         description: Query processed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                 count:
 *                   type: number
 *                   example: 25
 *                 query:
 *                   type: string
 *                   example: Show me workers from the IT department
 *                 queryInstructions:
 *                   type: object
 *                   description: The structured query instructions generated by AI
 *       400:
 *         description: Invalid request
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 error:
 *                   type: string
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 error:
 *                   type: string
 */
router.post('/query', authProvider.isAuthenticated.bind(authProvider), queryController.processQuery);

/**
 * @swagger
 * /api/upload-csv:
 *   post:
 *     summary: Upload CSV data and create database table
 *     description: Upload a CSV file to create a new table in the database. Only authenticated users can perform this action.
 *     tags: [Data]
 *     security:
 *       - cookieAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               csvFile:
 *                 type: string
 *                 format: binary
 *               tableName:
 *                 type: string
 *                 description: Optional custom table name
 *     responses:
 *       200:
 *         description: CSV uploaded and processed successfully
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Server error
 */
router.post('/upload-csv', authProvider.isAuthenticated.bind(authProvider), uploadController.uploadCSV);

module.exports = router;
