const express = require('express');
const router = express.Router();
const queryController = require('../controllers/queryController');

/**
 * @swagger
 * /api/health:
 *   get:
 *     summary: Health check endpoint
 *     description: Check if the Moogle API server is running and responsive
 *     tags: [Health]
 *     responses:
 *       200:
 *         description: Server is healthy and running
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: ok
 *                 message:
 *                   type: string
 *                   example: Moogle API is running
 *                 timestamp:
 *                   type: string
 *                   format: date-time
 *                   example: 2025-12-01T12:00:00.000Z
 */
router.get('/health', (req, res) => {
    res.json({
        status: 'ok',
        message: 'Moogle API is running',
        timestamp: new Date().toISOString()
    });
});

/**
 * @swagger
 * /api/query:
 *   post:
 *     summary: Process natural language query
 *     description: Convert natural language questions into structured queries and return filtered worker data
 *     tags: [Query]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - query
 *             properties:
 *               query:
 *                 type: string
 *                 description: Natural language question about worker data
 *                 example: Show me all workers from the IT department
 *                 minLength: 3
 *                 maxLength: 500
 *     responses:
 *       200:
 *         description: Query processed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                 count:
 *                   type: number
 *                   example: 25
 *                 query:
 *                   type: string
 *                   example: Show me workers from the IT department
 *                 queryInstructions:
 *                   type: object
 *                   description: The structured query instructions generated by AI
 *       400:
 *         description: Invalid request
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 error:
 *                   type: string
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 error:
 *                   type: string
 */
router.post('/query', queryController.processQuery);

module.exports = router;
